version: '3.1'

services:
  db:
    image: postgres
    container_name: ukrhumbat_back
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 101601630
      POSTGRES_DB: ukrhumbat
      POSTGRES_INITDB_ARGS: '-A md5'
    ports:
      - '5432:5432'
    volumes:
      - ./db:/db
      - ./db/setup.sh:/docker-entrypoint-initdb.d/setup.sh
